[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/Leonardo M SAP.pdf"
  to = "/download/sap"
  status = 301
  force = true

[[redirects]]
  from = "/Leonardo%20M%20SAP.pdf"
  to = "/download/sap"
  status = 301
  force = true

[[redirects]]
  from = "/Leonardo Front.pdf"
  to = "/download/front"
  status = 301
  force = true

[[redirects]]
  from = "/Leonardo%20Front.pdf"
  to = "/download/front"
  status = 301
  force = true

[[redirects]]
  from = "/Leonardo Front atual.pdf.pdf"
  to = "/download/front"
  status = 301
  force = true

[[redirects]]
  from = "/Leonardo%20Front%20atual.pdf.pdf"
  to = "/download/front"
  status = 301
  force = true
